#!/bin/bash

function check_dependencies {
	py_missing="Python version ~3.11 was not found on your system. Please install it and rerun this script. You can download the latest version from the official website: https://www.python.org/downloads/"
	npm_missing="Node.js/npm was not found. Please make sure you have installed Node.js version 16.0 or higher along with npm correctly. You can download Nodejs from here: https://nodejs.org/en/download"

	if [[ "$OSTYPE" == "darwin"* || "$OSTYPE" == "linux-gnu"* ]]; then

		if ! command -v npm &>/dev/null; then
			echo "$npm_missing"
			exit 1
		fi

		if command -v python &>/dev/null; then
			if ! python -c "import sys; exit(0) if sys.version_info >= (3,11) else exit(1)" &>/dev/null; then
				echo "$py_missing"
				exit 1
			fi
		else
			echo "$py_missing"
			exit 1
		fi
	fi
}
