codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: yes

coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    # - name: typescript
    #   statuses:
    #     - type: project
    #       target: 30%
    # - name: python
      statuses:
        - type: project
          target: 30%
    - name: cypress
      statuses:
        - type: project
          target: 30%
comment:
  layout: "reach, diff, flags, files"
  behaviour: default
  required_changes: no
