codecov:
  notify:
    after_n_builds: 3
    wait_for_ci: yes

coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: typescript
      statuses:
        - type: project
          target: 30%
    - name: python
      statuses:
        - type: project
          target: 30%
    - name: cypress
      statuses:
        - type: project
          target: 30%
ignore:
  - "src/setupTests.ts"
  - "src/**/*.test.tsx"
  - "src/**/*.cy.ts"
  - "src/**/*.cy.tsx"
  - "src/**/*.d.ts"
  - "./src/models"
  - "src/reportWebVitals.ts"

comment:
  layout: "reach, diff, flags, files"
  behaviour: default
  required_changes: no
