codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  status:
    patch: false
    project: false
flag_management:
  individual_flags:
    - name: cypress
      statuses:
        - target: 30.0
          type: project
    - name: python
      statuses:
        - target: 30.0
          type: project
comment:
  layout: "reach, diff, flags, files"
