codecov:
  notify:
    after_n_builds: 3
    wait_for_ci: yes

coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: typescript
      statuses:
        - type: project
          target: 30%
    - name: python
      statuses:
        - type: project
          target: 30%
    - name: visual
      statuses:
        - type: project
          target: 30%
