version: "3.9"


services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  rq-worker:
    image: onscene/flojoy-rq-worker:${RQ_WORKER_IMAGE_TAG}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  flojoy-watch:
    image: onscene/flojoy-watch:${WATCH_IMAGE_TAG}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  backend:
    image: onscene/flojoy-backend:${BACKEND_IMAGE_TAG}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose: 
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - rq-worker
