version: "3.9"


services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  rq-worker:
    image: shahadishraq/flojoy-rq-worker:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  backend:
    image: shahadishraq/flojoy-desktop:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose: 
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - rq-worker
