version: "3.9"


services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app_network

  backend:
    image: onscene/flojoy-backend:${BACKEND_IMAGE_TAG:-latest}
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose: 
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - app_network

  rq-worker:
    image: onscene/flojoy-rq-worker:${RQ_WORKER_IMAGE_TAG:-latest}
    restart: always
    environment:
      - BACKEND_HOST=backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - backend
    networks:
      - app_network

  flojoy-watch:
    image: onscene/flojoy-watch:${WATCH_IMAGE_TAG:-latest}
    restart: always
    environment:
      - BACKEND_HOST=backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - backend
    networks:
      - app_network

networks:
  app_network: