import { useEffect, useState } from "react";
import { Box, Collapse } from "@mantine/core";
import { Children } from "react";
import { twMerge } from "tailwind-merge";

type SidebarSectionProps = {
  title: string;
  depth: number;
  children: React.ReactNode;
  expand: boolean;
  collapse: boolean;
  icon?: React.ReactNode;
  color?: string;
  autogeneratedCategory?: boolean;
};

const SidebarSection = ({
  depth,
  title,
  children,
  expand,
  collapse,
  color,
  icon,
  autogeneratedCategory,
}: SidebarSectionProps) => {
  const [opened, setOpened] = useState(false);

  useEffect(() => {
    setOpened(true);
  }, [expand]);

  useEffect(() => {
    setOpened(false);
  }, [collapse]);

  if (Children.toArray(children).every((child) => child === null)) {
    return null;
  }

  return (
    <>
      <button
        onClick={() => setOpened((o) => !o)}
        className={`flex items-center w-11/12 px-2 py-2.5 max-h-10 mb-3 text-${color} bg-${color}/5 border border-${color}`}
        data-cy="sidebar-section-btn"
      >
        {icon}
        <div
          className={twMerge(
            "mr-auto ml-2 font-medium tracking-wide",
            autogeneratedCategory ? "font-mono" : ""
          )}
        >
          {title}
        </div>
      </button>
      <Collapse in={opened}>
        {/* padding according to the depth of the section */}
        <Box style={{ paddingLeft: `${10 + (depth + 1) * 5}px` }}>
          {children}
        </Box>
      </Collapse>
    </>
  );
};
export default SidebarSection;
