import { memo, useEffect, useRef, useState } from "react";

import { NodeElement, NodeSection } from "@src/utils/ManifestLoader";
import { LAYOUT_TOP_HEIGHT } from "@src/feature/common/Layout";
import { XIcon } from "lucide-react";
import { Button } from "@src/components/ui/button";
import { REQUEST_NODE_URL } from "@src/data/constants";
import { cn } from "@src/lib/utils";
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";

export type LeafClickHandler = (elem: NodeElement) => void;

// import { NumpySvg, ScipySvg } from "@src/assets/ArithmeticSVG";
import { cva } from "class-variance-authority";
import { ScrollArea } from "@src/components/ui/scroll-area";

export const sidebarVariants = cva("", {
  variants: {
    variant: {
      DATA: "text-accent2 bg-accent2/5 border-accent2",
      ETL: "text-accent1 bg-accent1/5 border-accent1",
      IO: "text-accent4 bg-accent4/5 border-accent4",
      LOGIC: "text-accent3 bg-accent3/5 border-accent3",
      AUTOGEN: "text-blue-500 bg-blue-500/5 border-blue-500",
    },
  },
});

export const categoryMap = {
  AI_ML: "DATA",
  GENERATORS: "DATA",
  VISUALIZERS: "DATA",
  EXTRACTORS: "ETL",
  TRANSFORMERS: "ETL",
  LOADERS: "ETL",
  INSTRUMENTS: "IO",
  LOGIC_GATES: "LOGIC",
  NUMPY: "AUTOGEN",
  SCIPY: "AUTOGEN",
  SKLEARN: "AUTOGEN",
};

// const autogeneratedCategories = ["NUMPY", "SCIPY", "SKLEARN"];
//
// const iconMap = {
//   NUMPY: <NumpySvg className="h-8 w-8" />,
//   SCIPY: <ScipySvg className="h-8 w-8" />,
// };

type SidebarProps = {
  isSideBarOpen: boolean;
  setSideBarStatus: React.Dispatch<React.SetStateAction<boolean>>;
  sections: NodeSection;
  leafNodeClickHandler: LeafClickHandler;
  customContent?: JSX.Element;
};

const Sidebar = ({
  isSideBarOpen,
  setSideBarStatus,
  sections,
  leafNodeClickHandler,
}: SidebarProps) => {
  const [query, setQuery] = useState("");

  console.log(sections);

  // These being booleans don't actually mean anything,
  // They just need to be values that can easily be changed in order
  // to trigger a useEffect in the children.
  // This is easily done by just toggling the booleans.
  const [expand, setExpand] = useState(false);
  const [collapse, setCollapse] = useState(false);

  const handleQueryChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
    if (e.target.value === "") {
      setCollapse(!collapse);
    } else {
      setExpand(!expand);
    }
  };

  const inputRef = useRef<HTMLInputElement>(null);
  const setFocus = () => {
    inputRef.current?.focus();
  };

  useEffect(() => {
    if (isSideBarOpen) {
      setFocus();
    }
  }, [isSideBarOpen]);

  return (
    <div
      data-testid="sidebar"
      style={{ height: `calc(100vh - ${LAYOUT_TOP_HEIGHT}px)` }}
      className={cn(
        "absolute z-50 flex w-96 flex-col bg-modal p-4",
        isSideBarOpen ? "left-0 duration-500" : "-left-full duration-300",
      )}
    >
      <div className="flex">
        <Input
          data-testid="sidebar-input"
          name="sidebar-input"
          placeholder="Search"
          type="search"
          value={query}
          onChange={handleQueryChange}
          className="w-auto grow"
        />
        <div className="px-1" />
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setSideBarStatus(false)}
        >
          <XIcon size={20} className="stroke-muted-foreground" />
        </Button>
      </div>

      <div className="py-1" />

      <div className="py-1" />

      <ScrollArea className="h-full min-w-full">
        {sections.children.map((levelOne) => {
          return (
            <div className="pl-2">
              <Collapsible>
                <CollapsibleTrigger>
                  <Button
                    className={cn(
                      "mt-1",
                      sidebarVariants({
                        variant: categoryMap[levelOne.key],
                      }),
                    )}
                  >
                    {levelOne.key}
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent>
                  {levelOne.entryType === "section" ? (
                    <>
                      {levelOne.children.map((levelTwo) => {
                        if (levelTwo.entryType === "section") {
                          return (
                            <div className="pl-4 text-sky-200">
                              <Collapsible>
                                <CollapsibleTrigger>
                                  <Button
                                    className={cn(
                                      "mt-1",
                                      sidebarVariants({
                                        variant: categoryMap[levelOne.key],
                                      }),
                                    )}
                                  >
                                    {levelTwo.key}
                                  </Button>
                                </CollapsibleTrigger>
                                <CollapsibleContent>
                                  {levelTwo.children.map((levelThree) => {
                                    if (levelThree.entryType === "section") {
                                      return (
                                        <div className="pl-6">
                                          <Button
                                            className={cn(
                                              "mt-1",
                                              sidebarVariants({
                                                variant:
                                                  categoryMap[levelOne.key],
                                              }),
                                            )}
                                          >
                                            {levelThree.key}
                                          </Button>
                                        </div>
                                      );
                                    } else {
                                      return (
                                        <div className="pl-6">
                                          <Button
                                            className={cn(
                                              "mt-1",
                                              sidebarVariants({
                                                variant:
                                                  categoryMap[levelOne.key],
                                              }),
                                            )}
                                            onClick={() =>
                                              leafNodeClickHandler(levelThree)
                                            }
                                          >
                                            {levelThree.key}
                                          </Button>
                                        </div>
                                      );
                                    }
                                  })}
                                </CollapsibleContent>
                              </Collapsible>
                            </div>
                          );
                        } else {
                          return <div className="pl-4">Leaf</div>;
                        }
                      })}
                    </>
                  ) : (
                    <div>Leaf</div>
                  )}
                </CollapsibleContent>
              </Collapsible>
            </div>
          );
        })}
      </ScrollArea>

      <div className="py-1" />

      <Button variant="outline" className="">
        <a
          href={REQUEST_NODE_URL}
          target="_blank"
          className="w-fit no-underline"
        >
          Missing a node? Request it here!
        </a>
      </Button>
    </div>
  );
};

export default memo(Sidebar);
