export enum API {
  saveBlocks = "SAVE_BLOCKS",
  updateBlocks = "UPDATE_BLOCKS",
  changeBlocksPath = "CHANGE_BLOCKS_PATH",
  checkPythonInstallation = "CHECK_PYTHON_INSTALLATION",
  installPipx = "INSTALL_PIPX",
  pipxEnsurepath = "PIPX_ENSUREPATH",
  installPoetry = "INSTALL_POETRY",
  installDependencies = "INSTALL_DEPENDENCIES",
  getPoetryVenvExecutable = "GET_POETRY_EXECUTABLE",
  spawnCaptain = "SPAWN_CAPTAIN",
  killCaptain = "KILL_CAPTAIN",
  openLogFolder = "OPEN_LOG_FOLDER",
  restartFlojoyStudio = "RESTART_STUDIO",
  setUnsavedChanges = "SET_UNSAVED_CHANGES",
  statusBarLogging = "STATUSBAR_LOGGING",
  setPythonInterpreter = "SET_PY_INTERPRETER",
  writeFileSync = "WRITE_FILE_SYNC",
  showSaveDialog = "SHOW_SAVE_DIALOG",
  browsePythonInterpreter = "BROWSE_PY_INTERPRETER",
  sendLogToStatusbar = "SEND_LOG_TO_STATUSBAR",
}
