export const useFlowChartState = jest.fn(() => ({
  rfInstance: {
    nodes: [],
  },
  nodes: [],
  edges: [],
  updateCtrlInputDataForNode: jest.fn(),
  removeCtrlInputDataForNode: jest.fn(),
  ctrlsManifest: [
    {
      type: "input",
      name: "Slider",
      id: "INPUT_PLACEHOLDER",
      hidden: false,
      minHeight: 1,
      minWidth: 2,
    },
  ],
  setCtrlsManifest: jest.fn(),
  isEditMode: false,
  gridLayout: [],
  setGridLayout: jest.fn(),
  setRfInstance: jest.fn(),
  loadFlowExportObject: jest.fn(),
  openFileSelector: jest.fn(),
  saveFile: jest.fn(),
  setIsEditMode: jest.fn(),
  uiTheme: "dark",
  setUiTheme: jest.fn(),
  showLogs: false,
  setShowLogs: jest.fn(),
  runningNode: "",
  setRunningNode: jest.fn(),
  failedNode: "",
  setFailedNode: jest.fn(),
  setEdges: jest.fn(),
  setNodes: jest.fn(),
}));
