type InstrumentThumbnailProps = {
  path: string;
  img: string;
  sectionSubRoot: string;
  label: string;
};

export default function InstrumentThumbnail({
  label,
  path,
  img,
}: InstrumentThumbnailProps) {
  const thumbnailPath = "examples/EX1/output.jpeg"; // Default thumbnail path is autogenerated app

  const imgSrc =
    img !== ""
      ? img
      : `https://raw.githubusercontent.com/flojoy-ai/docs/main/docs/nodes/${path}/${thumbnailPath}`;

  return (
    <div className="p-4">
      <a href={`/instruments-database/${path}/`}>
        <img
          className="mr-3 !h-[200px] w-[185px] object-scale-down"
          alt={label}
          src={imgSrc}
        />
        <p>{label}</p>
      </a>
    </div>
  );
}
