export enum Selectors {
  addBlockBtn = "add-block-button",
  sidebarInput = "sidebar-input",
  sidebarExpandBtn = "sidebar-expand-btn",
  sidebarCloseBtn = "sidebar-close",
  blockEditToggleBtn = "toggle-edit-mode",
  deleteBlockBtn = "delete-node-button",
  closeWelcomeModalBtn = "close-welcome-modal",
  clearCanvasBtn = "clear-canvas-button",
  clearCanvasConfirmBtn = "confirm-clear-canvas",
  playBtn = "btn-play",
  cancelPlayBtn = "btn-cancel",
  settingsBtn = "settings-btn",
  keyboardShortcutBtn = "btn-keyboardshortcut",
}
