name: CD

on:
  push:
    tags:
      # Build on every tag in the form v1.2.3-something.4
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildElectron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      DEBUG: electron-builder
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Run startup script
        run: bash flojoy -c
      
      - name: Download Micromamba executable (Win)
        if: startsWith(matrix.os, 'windows')
        run: |
          .\scripts\get_micromamba.ps1

      - name: Download Micromamba executable
        if: startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu')
        run: |
          bash scripts/get_micromamba.sh
        

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
