name: CI-UBUNTU-DOCKER

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildNode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.3.2

      - name: Npm install
        run: npm install --legacy-peer-deps
      
      - name: Run test
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          browser: chrome
          install: false

  testPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: pytest
        run: |
          cd PYTHON
          python -m pytest