name: Preview

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 4
          redis-port: 6379

      - name: Run Flojoy startup script
        run: bash flojoy -c

      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        shell: bash
      - run: unzip -qq ngrok-stable-linux-amd64.zip
        shell: bash
      - run: ./ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN}}
        shell: bash
      - run: npm run start-project && timeout 1h ./ngrok http 3000
        shell: bash
